export const BACKEND_JWT_ALGORITHM = 'HS256';
export const PERMISSION_CODES = {
  // 人员模块
  PEOPLE_LIST: 'PEOPLE_LIST',
  PEOPLE_INFO: 'PEOPLE_INFO',
  PEOPLE_CREATE: 'PEOPLE_CREATE',
  PEOPLE_UPDATE: 'PEOPLE_UPDATE',
  PEOPLE_DELETE: 'PEOPLE_DELETE',
  // 权限模块
  PERMISSION_LIST: 'PERMISSION_LIST',
  PERMISSION_INFO: 'PERMISSION_INFO',
  PERMISSION_CREATE: 'PERMISSION_CREATE',
  PERMISSION_UPDATE: 'PERMISSION_UPDATE',
  PERMISSION_DELETE: 'PERMISSION_LIST',
  // 角色模块
  ROLE_LIST: 'ROLE_LIST',
  ROLE_INFO: 'ROLE_INFO',
  ROLE_CREATE: 'ROLE_CREATE',
  ROLE_UPDATE: 'ROLE_UPDATE',
  ROLE_DELETE: 'ROLE_DELETE',
};
